Display Validator address, add bound to withdrawal derivation index, check deposit contract addresss.
LedgerHQ/app-ethereum pull request #133
Opened 2021-04-22 12:00 UTC by pscott

This PR adds three new features:
1. Display the validator address on screen when depositing.
2. Abort signing when the account index of the withdrawal  key is higher than `INDEX_MAX`.
3. Check that the `destination` field of the transaction is EXACTLY the same as the deposit contract address (sources for the address: [1](https://docs.ethhub.io/ethereum-roadmap/ethereum-2.0/deposit-contract/), [2](https://etherscan.io/address/0x00000000219ab540356cbb839cbe05303d7705fa), [3](https://ethereum.org/en/eth2/deposit-contract/))

2021-04-22 12:29 UTC, pscott commented on src_features/setEth2WithdrawalIndex/withdrawal_index.h
> +#define INDEX_MAX 1337  // scott
What value do we want to put in here ? 100 ? 1000 ?

2021-04-22 12:40 UTC, pscott commented on src_features/setEth2WithdrawalIndex/cmd_setEth2WithdrawalIndex.c
> +        THROW(0x6A80);  // scott throw this error code or create new one ?
My comment is to be addressed.... should we create a new error code ?

2021-05-04 10:02 UTC, TamtamHero requested changes

2021-05-04 10:23 UTC, TamtamHero approved these changes

2021-05-04 22:10 UTC, merged